#!/bin/bash

echo "=== UNSET TESTS ==="
unset ""; echo "unset empty_str: exit=$?"
unset =; echo "unset =: exit=$?"
unset "="; echo "unset quoted_eq: exit=$?"
unset "?"; echo "unset ?: exit=$?"
unset "TES.T"; echo "unset TES.T: exit=$?"
unset "TES+T"; echo "unset TES+T: exit=$?"
unset "TES=T"; echo "unset TES=T: exit=$?"
unset "TES-T"; echo "unset TES-T: exit=$?"
unset "-TEST"; echo "unset -TEST: exit=$?"
unset "TE*ST"; echo "unset TE*ST: exit=$?"
unset "============"; echo "unset ====: exit=$?"
unset "+++++++"; echo "unset ++++: exit=$?"

echo ""
echo "=== EXPORT TESTS ==="
export --TEST=123 2>/dev/null; echo "export --TEST=123: exit=$?"
export -TEST=100 2>/dev/null; echo "export -TEST=100: exit=$?"
export -TEST=123 2>/dev/null; echo "export -TEST=123: exit=$?"
export =============123 2>/dev/null; echo "export ====123: exit=$?"

echo ""
echo "=== UNSET STDERR CHECK ==="
unset "" 2>&1 | cat; echo "unset empty: exit=$?"
unset "=" 2>&1 | cat; echo "unset =: exit=$?"
unset "TES.T" 2>&1 | cat; echo "unset TES.T: exit=$?"
unset "-TEST" 2>&1 | cat; echo "unset -TEST: exit=$?"
